---
linters-settings:
  gocyclo:
    min-complexity: 15
  misspell:
    locale: "US"
  lll:
    line-length: 120
    tab-width: 4

linters:
  enable-all: true
  disable:
    - depguard
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - golint
    - interfacer
    - maligned
    - scopelint
    - stylecheck
    # TODO re-enable once we are finished with the current task
    - godox
    # TODO re-enable once we are finished with the current task
    - funlen
    # TODO re-enable once we are finished with the current task
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
