# docker-compose file for a local acmeproxy test environement.
#
# Initially copied from the pebble docker-compose.yaml file at
# https://github.com/letsencrypt/pebble/blob/master/docker-compose.yml
---
version: '3.7'
services:

  pebble:
    build:
      context: ../.pebble
      dockerfile: docker/pebble/linux.Dockerfile
    environment:
      PEBBLE_VA_NOSLEEP: 1
    command: pebble -config /test/config/pebble-config.json -strict -dnsserver 10.30.50.3:8053
    ports:
      - 14000:14000  # HTTPS ACME API
      - 15000:15000  # HTTPS Management API
    networks:
      acmeproxytest:
        ipv4_address: 10.30.50.2

  challtestsrv:
    build:
      context: ../.pebble
      dockerfile: docker/pebble-challtestsrv/linux.Dockerfile
    command: pebble-challtestsrv -defaultIPv6 "" -defaultIPv4 "${HOST_IP}"
    ports:
      - 8055:8055  # HTTP Management API
    networks:
      acmeproxytest:
        ipv4_address: 10.30.50.3

networks:
  acmeproxytest:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.50.0/24
