// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/api/grpcapi/internal/pb/error_details.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorDetails struct {
	Op   string `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Kind int32  `protobuf:"varint,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Msg  string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	// Types that are valid to be assigned to Err:
	//	*ErrorDetails_Plain
	//	*ErrorDetails_Nested
	Err                  isErrorDetails_Err `protobuf_oneof:"err"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ErrorDetails) Reset()         { *m = ErrorDetails{} }
func (m *ErrorDetails) String() string { return proto.CompactTextString(m) }
func (*ErrorDetails) ProtoMessage()    {}
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3e6af916b3620a1, []int{0}
}

func (m *ErrorDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDetails.Unmarshal(m, b)
}
func (m *ErrorDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDetails.Marshal(b, m, deterministic)
}
func (m *ErrorDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDetails.Merge(m, src)
}
func (m *ErrorDetails) XXX_Size() int {
	return xxx_messageInfo_ErrorDetails.Size(m)
}
func (m *ErrorDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDetails proto.InternalMessageInfo

func (m *ErrorDetails) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *ErrorDetails) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *ErrorDetails) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type isErrorDetails_Err interface {
	isErrorDetails_Err()
}

type ErrorDetails_Plain struct {
	Plain string `protobuf:"bytes,4,opt,name=plain,proto3,oneof"`
}

type ErrorDetails_Nested struct {
	Nested *ErrorDetails `protobuf:"bytes,5,opt,name=nested,proto3,oneof"`
}

func (*ErrorDetails_Plain) isErrorDetails_Err() {}

func (*ErrorDetails_Nested) isErrorDetails_Err() {}

func (m *ErrorDetails) GetErr() isErrorDetails_Err {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *ErrorDetails) GetPlain() string {
	if x, ok := m.GetErr().(*ErrorDetails_Plain); ok {
		return x.Plain
	}
	return ""
}

func (m *ErrorDetails) GetNested() *ErrorDetails {
	if x, ok := m.GetErr().(*ErrorDetails_Nested); ok {
		return x.Nested
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ErrorDetails) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ErrorDetails_Plain)(nil),
		(*ErrorDetails_Nested)(nil),
	}
}

func init() {
	proto.RegisterType((*ErrorDetails)(nil), "pb.ErrorDetails")
}

func init() {
	proto.RegisterFile("pkg/api/grpcapi/internal/pb/error_details.proto", fileDescriptor_d3e6af916b3620a1)
}

var fileDescriptor_d3e6af916b3620a1 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xc1, 0x6a, 0x84, 0x30,
	0x10, 0x86, 0x4d, 0x34, 0x42, 0xa7, 0xa5, 0x48, 0x0e, 0x25, 0x47, 0xe9, 0x49, 0x7a, 0x30, 0xd0,
	0xbe, 0x41, 0x69, 0xc1, 0x73, 0x5e, 0xa0, 0x24, 0x35, 0x48, 0xd0, 0x4d, 0x86, 0x31, 0xef, 0xb1,
	0xaf, 0xbc, 0x44, 0xf7, 0xb0, 0xa7, 0xf9, 0x67, 0xbe, 0x0f, 0xe6, 0x07, 0x8d, 0xeb, 0xa2, 0x2d,
	0x06, 0xbd, 0x10, 0xfe, 0x97, 0x19, 0x62, 0xf6, 0x14, 0xed, 0xa6, 0xd1, 0x69, 0x4f, 0x94, 0xe8,
	0x6f, 0xf6, 0xd9, 0x86, 0x6d, 0x1f, 0x91, 0x52, 0x4e, 0x92, 0xa3, 0x7b, 0xbf, 0x32, 0x78, 0xf9,
	0x2d, 0xec, 0xe7, 0x44, 0xf2, 0x15, 0x78, 0x42, 0xc5, 0x7a, 0x36, 0x3c, 0x19, 0x9e, 0x50, 0x4a,
	0x68, 0xd6, 0x10, 0x67, 0xc5, 0x7b, 0x36, 0x08, 0x73, 0x64, 0xd9, 0x41, 0x7d, 0xd9, 0x17, 0x55,
	0x1f, 0x52, 0x89, 0xf2, 0x0d, 0x04, 0x6e, 0x36, 0x44, 0xd5, 0x94, 0xdb, 0x54, 0x99, 0x73, 0x95,
	0x1f, 0xd0, 0x46, 0xbf, 0x67, 0x3f, 0x2b, 0xd1, 0xb3, 0xe1, 0xf9, 0xb3, 0x1b, 0xd1, 0x8d, 0x8f,
	0xff, 0xa6, 0xca, 0xdc, 0x8d, 0x6f, 0x01, 0xb5, 0x27, 0x72, 0xed, 0x51, 0xee, 0xeb, 0x16, 0x00,
	0x00, 0xff, 0xff, 0xdd, 0xf6, 0xca, 0x2d, 0xcf, 0x00, 0x00, 0x00,
}
