// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/db/internal/dbrecords/client.proto

package dbrecords

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Client struct {
	Id                   []byte             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountURL           string             `protobuf:"bytes,2,opt,name=accountURL,proto3" json:"accountURL,omitempty"`
	AccountKey           *Client_AccountKey `protobuf:"bytes,3,opt,name=accountKey,proto3" json:"accountKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_9830c6b62f7c7135, []int{0}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Client) GetAccountURL() string {
	if m != nil {
		return m.AccountURL
	}
	return ""
}

func (m *Client) GetAccountKey() *Client_AccountKey {
	if m != nil {
		return m.AccountKey
	}
	return nil
}

type Client_AccountKey struct {
	KeyType              uint32   `protobuf:"varint,1,opt,name=keyType,proto3" json:"keyType,omitempty"`
	KeyBytes             []byte   `protobuf:"bytes,2,opt,name=keyBytes,proto3" json:"keyBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client_AccountKey) Reset()         { *m = Client_AccountKey{} }
func (m *Client_AccountKey) String() string { return proto.CompactTextString(m) }
func (*Client_AccountKey) ProtoMessage()    {}
func (*Client_AccountKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_9830c6b62f7c7135, []int{0, 0}
}

func (m *Client_AccountKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client_AccountKey.Unmarshal(m, b)
}
func (m *Client_AccountKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client_AccountKey.Marshal(b, m, deterministic)
}
func (m *Client_AccountKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client_AccountKey.Merge(m, src)
}
func (m *Client_AccountKey) XXX_Size() int {
	return xxx_messageInfo_Client_AccountKey.Size(m)
}
func (m *Client_AccountKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Client_AccountKey.DiscardUnknown(m)
}

var xxx_messageInfo_Client_AccountKey proto.InternalMessageInfo

func (m *Client_AccountKey) GetKeyType() uint32 {
	if m != nil {
		return m.KeyType
	}
	return 0
}

func (m *Client_AccountKey) GetKeyBytes() []byte {
	if m != nil {
		return m.KeyBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*Client)(nil), "dbrecords.Client")
	proto.RegisterType((*Client_AccountKey)(nil), "dbrecords.Client.AccountKey")
}

func init() {
	proto.RegisterFile("pkg/db/internal/dbrecords/client.proto", fileDescriptor_9830c6b62f7c7135)
}

var fileDescriptor_9830c6b62f7c7135 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2b, 0xc8, 0x4e, 0xd7,
	0x4f, 0x49, 0xd2, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x4f, 0x49, 0x2a, 0x4a,
	0x4d, 0xce, 0x2f, 0x4a, 0x29, 0xd6, 0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x8b, 0x2b, 0xed, 0x62, 0xe4, 0x62, 0x73, 0x06, 0xcb, 0x09, 0xf1,
	0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x31, 0x65, 0xa6, 0x08, 0xc9,
	0x71, 0x71, 0x25, 0x26, 0x27, 0xe7, 0x97, 0xe6, 0x95, 0x84, 0x06, 0xf9, 0x48, 0x30, 0x29, 0x30,
	0x6a, 0x70, 0x06, 0x21, 0x89, 0x08, 0xd9, 0xc0, 0xe5, 0xbd, 0x53, 0x2b, 0x25, 0x98, 0x15, 0x18,
	0x35, 0xb8, 0x8d, 0x64, 0xf4, 0xe0, 0x46, 0xeb, 0x41, 0x8c, 0xd5, 0x73, 0x84, 0xab, 0x09, 0x42,
	0x52, 0x2f, 0xe5, 0xc4, 0xc5, 0x85, 0x90, 0x11, 0x92, 0xe0, 0x62, 0xcf, 0x4e, 0xad, 0x0c, 0xa9,
	0x2c, 0x48, 0x05, 0x3b, 0x80, 0x37, 0x08, 0xc6, 0x15, 0x92, 0xe2, 0xe2, 0xc8, 0x4e, 0xad, 0x74,
	0xaa, 0x2c, 0x49, 0x2d, 0x06, 0xbb, 0x81, 0x27, 0x08, 0xce, 0x4f, 0x62, 0x03, 0x7b, 0xc7, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x38, 0x43, 0x5e, 0xd2, 0xf8, 0x00, 0x00, 0x00,
}
