// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/db/internal/dbrecords/domain.proto

package dbrecords

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Domain struct {
	UserID               []byte   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CertificatePEM       []byte   `protobuf:"bytes,3,opt,name=certificatePEM,proto3" json:"certificatePEM,omitempty"`
	PrivateKeyPEM        []byte   `protobuf:"bytes,4,opt,name=privateKeyPEM,proto3" json:"privateKeyPEM,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Domain) Reset()         { *m = Domain{} }
func (m *Domain) String() string { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()    {}
func (*Domain) Descriptor() ([]byte, []int) {
	return fileDescriptor_8447184581058f96, []int{0}
}

func (m *Domain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Domain.Unmarshal(m, b)
}
func (m *Domain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Domain.Marshal(b, m, deterministic)
}
func (m *Domain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Domain.Merge(m, src)
}
func (m *Domain) XXX_Size() int {
	return xxx_messageInfo_Domain.Size(m)
}
func (m *Domain) XXX_DiscardUnknown() {
	xxx_messageInfo_Domain.DiscardUnknown(m)
}

var xxx_messageInfo_Domain proto.InternalMessageInfo

func (m *Domain) GetUserID() []byte {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *Domain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Domain) GetCertificatePEM() []byte {
	if m != nil {
		return m.CertificatePEM
	}
	return nil
}

func (m *Domain) GetPrivateKeyPEM() []byte {
	if m != nil {
		return m.PrivateKeyPEM
	}
	return nil
}

func init() {
	proto.RegisterType((*Domain)(nil), "dbrecords.Domain")
}

func init() {
	proto.RegisterFile("pkg/db/internal/dbrecords/domain.proto", fileDescriptor_8447184581058f96)
}

var fileDescriptor_8447184581058f96 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2b, 0xc8, 0x4e, 0xd7,
	0x4f, 0x49, 0xd2, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x4f, 0x49, 0x2a, 0x4a,
	0x4d, 0xce, 0x2f, 0x4a, 0x29, 0xd6, 0x4f, 0xc9, 0xcf, 0x4d, 0xcc, 0xcc, 0xd3, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x8b, 0x2b, 0x35, 0x31, 0x72, 0xb1, 0xb9, 0x80, 0xe5, 0x84, 0xc4,
	0xb8, 0xd8, 0x4a, 0x8b, 0x53, 0x8b, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0xa0,
	0x3c, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x30, 0x5b, 0x48, 0x8d, 0x8b, 0x2f, 0x39, 0xb5, 0xa8, 0x24, 0x33, 0x2d, 0x33, 0x39, 0xb1, 0x24,
	0x35, 0xc0, 0xd5, 0x57, 0x82, 0x19, 0xac, 0x07, 0x4d, 0x54, 0x48, 0x85, 0x8b, 0xb7, 0xa0, 0x28,
	0xb3, 0x2c, 0xb1, 0x24, 0xd5, 0x3b, 0xb5, 0x12, 0xa4, 0x8c, 0x05, 0xac, 0x0c, 0x55, 0x30, 0x89,
	0x0d, 0xec, 0x2c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0x11, 0x6c, 0x02, 0xc0, 0x00,
	0x00, 0x00,
}
