// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/db/internal/dbrecords/user.proto

package dbrecords

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   []byte           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountURL           string           `protobuf:"bytes,2,opt,name=accountURL,proto3" json:"accountURL,omitempty"`
	AccountKey           *User_AccountKey `protobuf:"bytes,3,opt,name=accountKey,proto3" json:"accountKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0c8482e1488dd84, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *User) GetAccountURL() string {
	if m != nil {
		return m.AccountURL
	}
	return ""
}

func (m *User) GetAccountKey() *User_AccountKey {
	if m != nil {
		return m.AccountKey
	}
	return nil
}

type User_AccountKey struct {
	KeyType              uint32   `protobuf:"varint,1,opt,name=keyType,proto3" json:"keyType,omitempty"`
	KeyBytes             []byte   `protobuf:"bytes,2,opt,name=keyBytes,proto3" json:"keyBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_AccountKey) Reset()         { *m = User_AccountKey{} }
func (m *User_AccountKey) String() string { return proto.CompactTextString(m) }
func (*User_AccountKey) ProtoMessage()    {}
func (*User_AccountKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0c8482e1488dd84, []int{0, 0}
}

func (m *User_AccountKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_AccountKey.Unmarshal(m, b)
}
func (m *User_AccountKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_AccountKey.Marshal(b, m, deterministic)
}
func (m *User_AccountKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_AccountKey.Merge(m, src)
}
func (m *User_AccountKey) XXX_Size() int {
	return xxx_messageInfo_User_AccountKey.Size(m)
}
func (m *User_AccountKey) XXX_DiscardUnknown() {
	xxx_messageInfo_User_AccountKey.DiscardUnknown(m)
}

var xxx_messageInfo_User_AccountKey proto.InternalMessageInfo

func (m *User_AccountKey) GetKeyType() uint32 {
	if m != nil {
		return m.KeyType
	}
	return 0
}

func (m *User_AccountKey) GetKeyBytes() []byte {
	if m != nil {
		return m.KeyBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "dbrecords.User")
	proto.RegisterType((*User_AccountKey)(nil), "dbrecords.User.AccountKey")
}

func init() {
	proto.RegisterFile("pkg/db/internal/dbrecords/user.proto", fileDescriptor_f0c8482e1488dd84)
}

var fileDescriptor_f0c8482e1488dd84 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0xc8, 0x4e, 0xd7,
	0x4f, 0x49, 0xd2, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x4f, 0x49, 0x2a, 0x4a,
	0x4d, 0xce, 0x2f, 0x4a, 0x29, 0xd6, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x84, 0x8b, 0x2a, 0x6d, 0x63, 0xe4, 0x62, 0x09, 0x2d, 0x4e, 0x2d, 0x12, 0xe2, 0xe3,
	0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x62, 0xca, 0x4c, 0x11, 0x92, 0xe3,
	0xe2, 0x4a, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x09, 0x0d, 0xf2, 0x91, 0x60, 0x52, 0x60, 0xd4,
	0xe0, 0x0c, 0x42, 0x12, 0x11, 0xb2, 0x82, 0xcb, 0x7b, 0xa7, 0x56, 0x4a, 0x30, 0x2b, 0x30, 0x6a,
	0x70, 0x1b, 0x49, 0xe9, 0xc1, 0x0d, 0xd6, 0x03, 0x19, 0xaa, 0xe7, 0x08, 0x57, 0x11, 0x84, 0xa4,
	0x5a, 0xca, 0x89, 0x8b, 0x0b, 0x21, 0x23, 0x24, 0xc1, 0xc5, 0x9e, 0x9d, 0x5a, 0x19, 0x52, 0x59,
	0x90, 0x0a, 0xb6, 0x9e, 0x37, 0x08, 0xc6, 0x15, 0x92, 0xe2, 0xe2, 0xc8, 0x4e, 0xad, 0x74, 0xaa,
	0x2c, 0x49, 0x2d, 0x06, 0xbb, 0x80, 0x27, 0x08, 0xce, 0x4f, 0x62, 0x03, 0x7b, 0xc5, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x63, 0x9c, 0x1b, 0x64, 0xf2, 0x00, 0x00, 0x00,
}
